// CARS  DA HOME COMO; CARD DE IA, CRIAR, ETC, ESTÁ NA PASTA COMPOENNTES
// AINDA FALTA LIGAR AS TELAS COM NAVIGATOR, FALTA CRIAR A TELA DE CONSULTAR, QUE É UMA RÉPLICA DA TELA DETALHES DO CASO PERICIAL,
//  QUE SERIA A TELA detalhes-do-caso.js, que está pronta, só muda umas informções e menos (-) cards, resumindo:
//  a home está pronta.
// detalhes do caso pericial que é a tela que aparece ao clicar em visualizar, está pronta.
// tela de banco de dados está pronta. 

//FALTA: TELA DE EVIDENCIA..CRIAR, LAUDOS, EXPORTAR, EDITAR, TODOS OS COMPONENTES DENTRO DO CARD CRIAR CASO. 
// E TAMBEM A TELA DE PERFIL

// TBM O FOOTER. 

//OBS: O ARQUIVO HOME2 É O OFICIAL. A HOME.JS ESTÁ SENDO 
// USADA PARA VISUALIZAR A TELA NO EXPO, POIS AS TELAS NÃO ESTÃO LIGADAS E SEM ISSO, NÃO DÁ PRA VISUALIZAR.

// ERROS NO CONSOLE DO LOCAL HOST: NÃO ESTÁ DANDO PRA VISUAZLIZAR AS TELAS PELO LOCAL HOST.
//OBS2: PARA VISUAZLIZAR AS TELAS PRONTAS: DETALHES-DO-CASO.JS, HOME2, E BANCODECASO,
//  COPIE E COLE O CODIGO E COLE NA HOME.JS 